theme = "base16_transparent"

[editor]
scrolloff = 3
scroll-lines = 1
color-modes = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.gutters]
layout = ["diagnostics", "line-numbers", "diff"]

[editor.gutters.line-numbers]
min-width = 1

[keys.normal]
"Meta-up" = "goto_prev_paragraph"
"Meta-down" = "goto_next_paragraph"

[keys.select]
"Meta-up" = "goto_prev_paragraph"
"Meta-down" = "goto_next_paragraph"
