[default]
depends = [
    "git",
    "shell",
    "helix",
    "nvim",
    "rime",
    "nix",
    "misc",
    "secret",
    "brew",
]

[shell.files]
"shell/carapace" = "~/Library/Application Support/carapace/"
"shell/ghostty.conf" = "~/Library/Application Support/com.mitchellh.ghostty/config"
"shell/nushell" = "~/Library/Application Support/nushell/"

[rime.files]
# "rime" = "~/.local/share/fcitx5/rime/"
"rime" = "~/Library/Rime/"
"rime/options.macos.yaml" = "~/Library/Rime/options.platform.yaml"

[misc.files]
"misc/.pycodestyle" = "~/.config/pycodestyle"

[brew.files]
"brew" = "/opt/homebrew/Library/Taps/balthild/homebrew-dotfiles"
